import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { useEffect, useState } from "react";
import DarkModeToggle from "./DarkModeToggle";
import Link from "next/link";
import { FaUser, FaThLarge } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopNav() {
  return (
    <nav className="fixed top-4 left-1/2 -translate-x-1/2 z-40 flex gap-4 bg-white/60 dark:bg-gray-900/60 rounded-full shadow-xl px-8 py-3 items-center backdrop-blur-lg border border-gray-200 dark:border-gray-800 ring-1 ring-blue-100/40 dark:ring-blue-900/30">
      <Link href="/dashboard" className="flex items-center gap-2 font-semibold text-blue-600 dark:text-blue-300 hover:underline">
        <FaThLarge className="inline text-lg" /> <span>Dashboard</span>
      </Link>
      <Link href="/profile" className="flex items-center gap-2 font-semibold text-blue-600 dark:text-blue-300 hover:underline">
        <FaUser className="inline text-lg" /> <span>Profile</span>
      </Link>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-gradient-to-br from-blue-100/60 via-pink-50/60 to-white dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 text-gray-900 dark:text-white transition-colors ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <DarkModeToggle />
        <TopNav />
        <div className="pt-24">{children}</div>
      </body>
    </html>
  );
}
